#TravisCI details
language: android



android:
  components:
  # Uncomment the lines below if you want to
      # use the latest revision of Android SDK Tools
    - tools
    - tools
    - build-tools-27.0.3

script:
   - gradle build connectedCheck --daemon
   - ant debug install test










